### ISSUE TITLE
Cannot save into fields

### ISSUE THREAD

**Issue by JStika** [silverstripe-labs/silverstripe-iframe#3]
Why Iframe module cannot save into fields?
Content
BottomContent

**Comment by assertchris** [comment]
Closing this for now. If you are still having this issue then we're going to need some more info. :)

**Comment by tractorcow** [comment]
I've tested this feature and I can confirm that you can indeed save into fields. Possibly there is some configuration in your project.

In any case, I apologise for not answering this for 2 years.
