### ISSUE TITLE
Iframe not showing in Firefox

### ISSUE THREAD

**Issue by benmanu** [silverstripe-labs/silverstripe-iframe#6]
Have run into an issue in Firefox where the Iframe doesn't display, the Iframe content loads fine but the .load() event isn't triggered in iframe_page.js resulting in "Loading content..." to be always shown. This is intermittent, about 50% of the time it doesn't work.

Replicated in FF 32, 35, and 38.

**Comment by brettt89** [comment]
I am also getting this issue on IE9

**Comment by tractorcow** [comment]
Fixed with #7
